listen: :8443
tls:
  cert: /root/ssl/server.cer
  key: /root/ssl/server.key
auth:
  type: password
  password: xiaoye
resolver:
  type: tcp
  tcp:
    addr: 8.8.8.8:53
    timeout: 4s
acl:
  inline:
    - reject(all, udp/443)
masquerade:
  type: proxy
  proxy:
    url: https://www.apple.com
    rewriteHost: true
outbounds:
  - name: xray
    type: socks5
    socks5:
      addr: 127.0.0.1:1080
