name: frp

on:
  push:
    paths:
    - frp/**
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: version
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        export VERSION=$(curl https://api.github.com/repos/fatedier/frp/releases/latest | grep "tag_name" | cut -d\" -f4 | sed "s/^v//")
        docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/frp:${VERSION} > /dev/null && echo "" || echo "::set-output name=version::${VERSION}"
  publish:
    needs: update
    if: ${{ needs.update.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        build-args: |
          VERSION=${{ needs.update.outputs.version }}
        context: frp
        file: frp/Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/frp
          ${{ secrets.DOCKERHUB_USERNAME }}/frp:${{ needs.update.outputs.version }}
