name: sing-box

on:
  push:
    paths:
    - sing-box/**
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: version
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        export VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases | grep -m1 "tag_name" | cut -d\" -f4 | sed "s/^v//")
        docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/sing-box:${VERSION} > /dev/null && echo "" || echo "version=${VERSION}" >> $GITHUB_OUTPUT
  publish:
    needs: update
    if: ${{ needs.update.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        build-args: |
          VERSION=${{ needs.update.outputs.version }}
        context: sing-box
        file: sing-box/Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/sing-box
          ${{ secrets.DOCKERHUB_USERNAME }}/sing-box:${{ needs.update.outputs.version }}
